spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/self_introduce
    username : root
    password : 921218
  application:
    name: self-introduce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

admin:
  username:  admin
  password:  921218

app:
  cors:
    allowed-origin:  "http://localhost:35729"